### ISSUE TITLE
required to transform NightClock

### ISSUE THREAD

**Issue by francescaneri** [arbox0/NightClock#1]
Hi, you can move the numbers of blood sugar levels in line with the other numbers in order to expand more space vision of blood sugar levels? and have a chance to read it vertically? and space out a little more on the day with the time and keep the same character of the alarm? congratulations for the project. nice idea to be able to enlarge the screen at will of blood sugar levels. if you can Alvare the limit up to 400 the number of days to do it in bold to differentiate it from time. thank you very much Matteo

**Comment by francescaneri** [comment]
i forgot....if you could put the percentage of the battery of the phone as a pebble....in the nightwidget to the percentage of the micro ;) 
there is no refresh button when arrive the notification of new glucose
I am a user not a programmer. sorry Matteo

**Comment by arbox0** [comment]
Ok,

-I'll see how to put it vertically, at first it was intended to be only a "landscape" app... but I suppose I can change that.
- I Can give more space between date and time and keep the same font for the alarm. However I can't do too many changes because android layout is pretty limiting.

I have a problem moving Blood sugar levels in line with the others... This change would move SGV values to the left, to give more space to the MBG, or all the numbers would be too close between them which, in my opinion, would be confusing and overloaded...

I don't quite understand the last sentence..."if you can Alvare the limit up to 400 the number of days to do it in bold to differentiate it from time"

I don't know how pebble is showing the uploader battery. I am not using the pebble, and I am not a pebble project developer, so I'll have to check how are they showing that info to know If I can do something similar.

Regards
